#!/usr/bin/python
# -*- coding: utf8 -*-
# Author: Alexander Malaev <scream@spuge.net>
# Description:
# This script reads haproxy stat, generated by command:
# echo "show stat" | /usr/bin/socat stdio unix-connect:/var/lib/haproxy/stats > haproxy.stat
# and creates defined items for all clusters and servers in it.
#

from zabbix_utils.options import get_options
from zabbix_utils.providers.haproxy import HaproxyDataProvider

if  __name__ == "__main__":
    options, args = get_options()
    ip = HaproxyDataProvider(options, 'Template_App_Haproxy_Stats')
    ip.addFromFile('haproxy.stat')
    ip.createItems()
